// Column definitions for all mass-upload datasets.
// This file is the single source of truth for upload column schemas.
// DATASETS array stays in srv/mass-upload.js (the orchestrator).

function column(name, type, options = {}) {
  return {
    name,
    type,
    required: Boolean(options.required)
  }
}

function lookupDataset(name, label, description) {
  const { importLookupRows } = require('./lookup-importer')
  return {
    name,
    label,
    description,
    entity: `bridge.management.${name}`,
    columns: LOOKUP_COLUMNS,
    orderBy: 'code',
    importer: importLookupRows,
    templateOnly: true
  }
}

const LOOKUP_COLUMNS = [
  column('code', 'string', { required: true }),
  column('name', 'string'),
  column('descr', 'string')
]

const ALLOWED_VALUES_COLUMNS = [
  column('entityName', 'string', { required: true }),
  column('code',       'string', { required: true }),
  column('label',      'string'),
  column('description','string'),
  column('active',     'boolean')
]

const ALLOWED_VALUES_WHITELIST = new Set([
  'ConditionStates', 'ConditionTrends', 'ConditionSummaries', 'StructuralAdequacyTypes',
  'PostingStatuses', 'CapacityStatuses', 'AssetClasses', 'StructureTypes', 'DesignLoads',
  'States', 'Regions', 'InspectionTypes', 'ScourRiskLevels', 'PbsApprovalClasses',
  'RestrictionTypes', 'RestrictionStatuses', 'VehicleClasses', 'RestrictionCategories',
  'RestrictionUnits', 'RestrictionDirections', 'SurfaceTypes', 'SubstructureTypes',
  'FoundationTypes', 'WaterwayTypes', 'FatigueDetailCategories', 'DefectCodes'
])

const BRIDGE_COLUMNS = [
  column('ID', 'integer'),
  column('descr', 'string'),
  column('bridgeId', 'string'),
  column('bridgeName', 'string', { required: true }),
  column('assetClass', 'string'),
  column('route', 'string'),
  column('routeNumber', 'string'),
  column('state', 'string', { required: true }),
  column('region', 'string'),
  column('lga', 'string'),
  column('latitude', 'decimal', { required: true }),
  column('longitude', 'decimal', { required: true }),
  column('location', 'string'),
  column('assetOwner', 'string', { required: true }),
  column('managingAuthority', 'string'),
  column('structureType', 'string'),
  column('yearBuilt', 'integer'),
  column('designLoad', 'string'),
  column('designStandard', 'string'),
  column('clearanceHeight', 'decimal'),
  column('spanLength', 'decimal'),
  column('material', 'string'),
  column('spanCount', 'integer'),
  column('totalLength', 'decimal'),
  column('deckWidth', 'decimal'),
  column('numberOfLanes', 'integer'),
  column('condition', 'string'),
  column('conditionRating', 'integer'),
  column('structuralAdequacyRating', 'integer'),
  column('postingStatus', 'string'),
  column('conditionStandard', 'string'),
  column('seismicZone', 'string'),
  column('asBuiltDrawingReference', 'string'),
  column('scourDepthLastMeasured', 'decimal'),
  column('floodImmunityAriYears', 'integer'),
  column('floodImpacted', 'boolean'),
  column('highPriorityAsset', 'boolean'),
  column('remarks', 'string'),
  column('status', 'string'),
  column('scourRisk', 'string'),
  column('lastInspectionDate', 'date'),
  column('nhvrAssessed', 'boolean'),
  column('nhvrAssessmentDate', 'date'),
  column('loadRating', 'decimal'),
  column('pbsApprovalClass', 'string'),
  column('importanceLevel', 'integer'),
  column('averageDailyTraffic', 'integer'),
  column('heavyVehiclePercent', 'decimal'),
  column('gazetteReference', 'string'),
  column('nhvrReferenceUrl', 'string'),
  column('freightRoute', 'boolean'),
  column('overMassRoute', 'boolean'),
  column('hmlApproved', 'boolean'),
  column('bDoubleApproved', 'boolean'),
  column('dataSource', 'string'),
  column('sourceReferenceUrl', 'string'),
  column('openDataReference', 'string'),
  column('sourceRecordId', 'string'),
  column('restriction_ID', 'string'),
  column('geoJson', 'string'),
  column('inspectionType', 'string'),
  column('inspectionFrequencyYears', 'integer'),
  column('nextInspectionDue', 'date'),
  column('conditionTrend', 'string'),
  column('surfaceType', 'string'),
  column('substructureType', 'string'),
  column('foundationType', 'string'),
  column('waterwayType', 'string'),
  column('pbsApprovalDate', 'date'),
  column('pbsApprovalExpiry', 'date'),
  column('hmlApprovalDate', 'date'),
  column('hmlApprovalExpiry', 'date'),
  column('gazetteEffectiveDate', 'date'),
  column('gazetteExpiryDate', 'date'),
  column('postingStatusReason', 'string'),
  column('closureDate', 'date'),
  column('closureEndDate', 'date'),
  column('closureReason', 'string'),
  column('precinct', 'string'),
  column('spansOver', 'string'),
  column('locality', 'string'),
  column('facilityTypeCode', 'string'),
  column('operationalStatusCode', 'string'),
  column('structuralDeficiencyCode', 'string'),
  column('deficiencyComments', 'string'),
  column('loadLimitTruck', 'decimal'),
  column('loadLimitSemitrailer', 'decimal'),
  column('isActive', 'boolean', { description: 'Set to false to soft-deactivate this bridge (hides from operational views)' })
]

const RESTRICTION_COLUMNS = [
  column('ID', 'string'),
  column('parent_ID', 'string'),
  column('restrictionRef', 'string', { required: true }),
  column('bridgeRef', 'string'),
  column('bridge_ID', 'integer'),
  column('name', 'string'),
  column('descr', 'string'),
  column('restrictionCategory', 'string', { required: true }),
  column('restrictionType', 'string', { required: true }),
  column('restrictionValue', 'string'),
  column('restrictionUnit', 'string'),
  column('restrictionStatus', 'string', { required: true }),
  column('appliesToVehicleClass', 'string'),
  column('grossMassLimit', 'decimal'),
  column('axleMassLimit', 'decimal'),
  column('heightLimit', 'decimal'),
  column('widthLimit', 'decimal'),
  column('lengthLimit', 'decimal'),
  column('speedLimit', 'integer'),
  column('permitRequired', 'boolean'),
  column('escortRequired', 'boolean'),
  column('temporary', 'boolean'),
  column('active', 'boolean'),
  column('effectiveFrom', 'date'),
  column('effectiveTo', 'date'),
  column('approvedBy', 'string'),
  column('direction', 'string'),
  column('enforcementAuthority', 'string'),
  column('temporaryFrom', 'date'),
  column('temporaryTo', 'date'),
  column('temporaryReason', 'string'),
  column('approvalReference', 'string'),
  column('issuingAuthority', 'string'),
  column('legalReference', 'string'),
  column('remarks', 'string'),
  column('postingSignId', 'string'),
  column('gazetteNumber', 'string'),
  column('gazettePublicationDate', 'date'),
  column('gazetteExpiryDate', 'date'),
  column('loadLimitOrderRef', 'string'),
  column('loadLimitOrderDate', 'date'),
  column('loadLimitOrderExpiry', 'date'),
  column('pilotVehicleCount', 'integer')
]

const INSPECTION_COLUMNS = [
  column('ID',                              'string'),
  column('bridgeRef',                       'string',  { required: true }),
  column('inspectionRef',                   'string',  { description: 'Auto-generated INS-NNNN if blank' }),
  column('inspectionDate',                  'date',    { required: true }),
  column('inspectionType',                  'string',  { required: true, description: 'Routine | Detailed | Principal | Special | Post-Event' }),
  column('inspector',                       'string',  { required: true }),
  column('inspectorAccreditationNumber',    'string'),
  column('inspectorAccreditationLevel',     'string',  { description: 'Level 1 | Level 2 | Level 3 | Level 4' }),
  column('inspectorCompany',                'string'),
  column('qualificationExpiry',             'date'),
  column('inspectionScope',                 'string'),
  column('inspectionStandard',              'string',  { description: 'AS5100-7 | AGAM | TfNSW-BIM | Other' }),
  column('inspectionMethodology',           'string',  { description: 'Visual | Under-Bridge Unit | Rope Access | Underwater | Drone' }),
  column('weatherConditions',               'string'),
  column('accessibilityIssues',             'string'),
  column('overallConditionRating',          'integer', { description: '1–10 overall condition' }),
  column('overallStructuralAdequacy',       'string',  { description: 'Adequate | Marginal | Inadequate' }),
  column('loadCarryingCapacityConfirmed',   'boolean', { description: 'true = posted capacity still valid (AS 5100-7 §3.2)' }),
  column('criticalFindings',                'boolean', { description: 'true = critical findings requiring immediate action' }),
  column('followUpRequired',                'boolean', { description: 'true = follow-up inspection / action required' }),
  column('recommendedActions',              'string'),
  column('nextInspectionRecommended',       'date'),
  column('reportIssueDate',                 'date'),
  column('reportStorageRef',                'string'),
  column('s4InspectionOrderRef',            'string'),
  column('s4NotificationRef',               'string'),
  column('inspectionNotes',                 'string'),
  column('active', 'boolean', { description: 'Set to false to soft-deactivate this inspection record' })
]

const ELEMENT_COLUMNS = [
  column('ID',                        'string'),
  column('bridgeRef',                 'string',  { required: true }),
  column('elementId',                 'string',  { required: true }),
  column('elementType',               'string',  { required: true }),
  column('elementName',               'string',  { required: true }),
  column('spanNumber',                'integer'),
  column('pierNumber',                'integer'),
  column('position',                  'string'),
  column('currentConditionRating',    'integer'),
  column('conditionRatingDate',       'date'),
  column('conditionTrend',            'string'),
  column('material',                  'string'),
  column('yearConstructed',           'integer'),
  column('yearLastRehabbed',          'integer'),
  column('maintenanceRequired',       'boolean'),
  column('urgencyLevel',              'string'),
  column('estimatedRepairCost',       'decimal'),
  column('s4EquipmentNumber',         'string'),
  column('notes',                     'string')
]

const BRIDGE_RESTRICTION_COLUMNS = [
  column('ID',                        'string'),
  column('bridgeRef',                 'string',  { required: true }),
  column('restrictionRef',            'string',  { required: true }),
  column('name',                      'string',  { required: true }),
  column('descr',                     'string'),
  column('restrictionCategory',       'string'),
  column('restrictionType',           'string'),
  column('restrictionValue',          'string'),
  column('restrictionUnit',           'string'),
  column('appliesToVehicleClass',     'string'),
  column('grossMassLimit',            'decimal'),
  column('axleMassLimit',             'decimal'),
  column('heightLimit',               'decimal'),
  column('widthLimit',                'decimal'),
  column('lengthLimit',               'decimal'),
  column('speedLimit',                'integer'),
  column('permitRequired',            'boolean'),
  column('active',                    'boolean'),
  column('effectiveFrom',             'date'),
  column('effectiveTo',               'date'),
  column('approvedBy',                'string'),
  column('direction',                 'string')
]

const RST_PROVISION_COLUMNS = [
  column('ID',              'string'),
  column('restrictionRef', 'string',  { required: true }),
  column('provisionCode',  'string',  { required: true }),
  column('description',    'string'),
  column('sortOrder',      'integer'),
  column('active',         'boolean')
]

const PROVISION_COLUMNS = [
  column('ID',              'string'),
  column('restrictionRef', 'string',  { required: true }),
  column('provisionNumber', 'integer'),
  column('provisionType',  'string'),
  column('provisionText',  'string',  { required: true }),
  column('vehicleClasses', 'string'),
  column('timeOfDay',      'string'),
  column('seasonalPeriod', 'string'),
  column('effectiveFrom',  'date'),
  column('effectiveTo',    'date'),
  column('approvedBy',     'string'),
  column('legalReference', 'string'),
  column('active',         'boolean')
]

const LRC_COLUMNS = [
  column('ID',                        'string'),
  column('bridgeRef',                 'string',  { required: true }),
  column('certificateNumber',         'string',  { required: true }),
  column('certificateVersion',        'integer'),
  column('status',                    'string'),
  column('ratingStandard',            'string',  { required: true }),
  column('ratingLevel',               'string',  { required: true }),
  column('certifyingEngineer',        'string',  { required: true }),
  column('engineerQualification',     'string',  { required: true }),
  column('engineerLicenseNumber',     'string'),
  column('engineerOrganisation',      'string'),
  column('rfT44',                     'decimal'),
  column('rfSM1600',                  'decimal'),
  column('rfHML',                     'decimal'),
  column('rfHLP400',                  'decimal'),
  column('dynamicLoadAllowance',      'decimal'),
  column('fatigueSensitive',          'boolean'),
  column('certificateIssueDate',      'date',    { required: true }),
  column('certificateExpiryDate',     'date',    { required: true }),
  column('nextReviewDate',            'date'),
  column('notes',                     'string')
]

const CONDITION_SURVEY_COLUMNS = [
  column('bridgeRef',                  'string',  { required: true }),
  column('surveyRef',                  'string'),
  column('surveyDate',                 'date',    { required: true }),
  column('surveyType',                 'string',  { required: true }),
  column('surveyedBy',                 'string',  { required: true }),
  column('conditionRating',            'integer', { required: true }),
  column('structuralRating',           'integer'),
  column('overallGrade',               'string'),
  column('inspectorAccreditationLevel','string'),
  column('accessMethod',               'string'),
  column('nextSurveyRecommended',      'date'),
  column('estimatedRehabCost',         'decimal'),
  column('actionPlan',                 'string'),
  column('linkedInspectionRef',        'string'),
  column('programmeYear',              'integer'),
  column('status',                     'string'),
  column('notes',                      'string'),
  column('remarks',                    'string'),
  column('active',                     'boolean'),
]

const LOAD_RATING_COLUMNS = [
  column('bridgeRef',              'string',  { required: true }),
  column('ratingRef',              'string'),
  column('vehicleClass',           'string',  { required: true }),
  column('ratingMethod',           'string',  { required: true }),
  column('ratingFactor',           'decimal'),
  column('grossMassLimit',         'decimal'),
  column('assessedBy',             'string',  { required: true }),
  column('assessmentDate',         'date',    { required: true }),
  column('validTo',                'date',    { required: true }),
  column('ratingEngineerNer',      'string'),
  column('governingMember',        'string'),
  column('governingFailureMode',   'string'),
  column('dynamicLoadAllowance',   'decimal'),
  column('reportRef',              'string'),
  column('status',                 'string'),
  column('remarks',                'string'),
  column('active',                 'boolean'),
]

const PERMIT_COLUMNS = [
  column('bridgeRef',             'string',  { required: true }),
  column('permitRef',             'string'),
  column('permitType',            'string',  { required: true }),
  column('applicantName',         'string',  { required: true }),
  column('nhvrPermitNumber',      'string'),
  column('nhvrApplicationNumber', 'string'),
  column('vehicleClass',          'string'),
  column('grossMass',             'decimal'),
  column('height',                'decimal'),
  column('width',                 'decimal'),
  column('length',                'decimal'),
  column('tripCount',             'integer'),
  column('axleConfiguration',     'string'),
  column('escortRequired',        'boolean'),
  column('pilotVehicleCount',     'integer'),
  column('appliedDate',           'date'),
  column('validFrom',             'date'),
  column('validTo',               'date'),
  column('status',                'string'),
  column('decisionBy',            'string'),
  column('decisionDate',          'date'),
  column('conditionsOfApproval',  'string'),
  column('remarks',               'string'),
  column('active',                'boolean'),
]

const DEFECT_COLUMNS = [
  column('ID',                        'string'),
  column('bridgeRef',                 'string',  { required: true,  description: 'Bridge reference e.g. BRG-NSW-001' }),
  column('inspectionRef',             'string',  { description: 'Link to inspection (INS-NNNN) — optional' }),
  column('defectId',                  'string',  { description: 'Auto-generated DEF-NNNN if blank' }),
  column('defectType',                'string',  { required: true }),
  column('defectDescription',         'string',  { required: true }),
  column('severity',                  'integer', { required: true,  description: '1=Low 2=Medium 3=High 4=Critical' }),
  column('urgency',                   'integer', { required: true,  description: '1=Low 2=Medium 3=Urgent 4=Emergency' }),
  column('bridgeElement',             'string',  { description: 'Element location description' }),
  column('defectCode',                'string',  { description: 'SIMS defect code e.g. BS01' }),
  column('deteriorationMechanism',    'string',  { description: 'Corrosion | Fatigue | Impact | Scour | Overload | Chemical | Settlement | Aging' }),
  column('spanNumber',                'integer'),
  column('pierNumber',                'integer'),
  column('face',                      'string'),
  column('position',                  'string'),
  column('dimensionLengthMm',         'decimal'),
  column('dimensionWidthMm',          'decimal'),
  column('dimensionDepthMm',          'decimal'),
  column('remediationStatus',         'string',  { description: 'Open | In Progress | Closed | Deferred' }),
  column('estimatedRepairCost',       'decimal', { description: 'AUD' }),
  column('plannedRemediationDate',    'date'),
  column('repairMethod',              'string',  { description: 'SIMS repair method code' }),
  column('maintenancePriority',       'string',  { description: 'P1=Emergency P2=Urgent P3=Routine P4=Planned' }),
  column('requiresLoadRestriction',   'boolean', { description: 'true triggers a capacity review alert' }),
  column('notes',                     'string'),
  column('active', 'boolean', { description: 'Set to false to soft-deactivate this defect record' })
]

const CAPACITY_COLUMNS = [
  column('ID',                        'string'),
  column('bridgeRef',                 'string',  { required: true }),
  column('capacityType',              'string',  { required: true, description: 'e.g. AS 5100.7 | AS 1170 | Posted' }),
  column('grossMassLimit',            'decimal', { description: 'Gross Mass Limit (t)' }),
  column('grossCombined',             'decimal', { description: 'Gross Combined Mass (t)' }),
  column('steerAxleLimit',            'decimal'),
  column('singleAxleLimit',           'decimal'),
  column('tandemGroupLimit',          'decimal'),
  column('triAxleGroupLimit',         'decimal'),
  column('axleSpacingMinimumM',       'decimal'),
  column('minClearancePosted',        'decimal', { description: 'Min posted clearance (m)' }),
  column('lane1Clearance',            'decimal'),
  column('lane2Clearance',            'decimal'),
  column('clearanceSurveyDate',       'date'),
  column('clearanceSurveyMethod',     'string'),
  column('carriagewayWidth',          'decimal'),
  column('trafficableWidth',          'decimal'),
  column('laneWidth',                 'decimal'),
  column('ratingStandard',            'string',  { description: 'e.g. AS 5100.7:2017' }),
  column('ratingFactor',              'decimal'),
  column('ratingEngineer',            'string'),
  column('ratingDate',                'date'),
  column('nextReviewDue',             'date'),
  column('reportReference',           'string'),
  column('effectiveFrom',             'date',    { required: true }),
  column('effectiveTo',               'date'),
  column('engineeringNotes',          'string'),
  column('active', 'boolean', { description: 'Set to false to soft-deactivate this capacity record' })
]

const SCOUR_COLUMNS = [
  column('ID',                           'string'),
  column('bridgeRef',                    'string',  { required: true }),
  column('assessmentDate',               'date',    { required: true }),
  column('assessmentType',               'string',  { required: true, description: 'Routine | Post-Flood | Detailed | Desktop' }),
  column('scourRisk',                    'string',  { required: true, description: 'Low | Medium | High | Extreme' }),
  column('measuredDepth',                'decimal', { description: 'Measured scour depth (m)' }),
  column('criticalScourDepthM',          'decimal', { description: 'AP-G71.8 §5.1 critical scour depth (m)' }),
  column('floodImmunityAriYears',        'integer'),
  column('waterwayType',                 'string'),
  column('foundationType',               'string'),
  column('scourCountermeasureType',      'string'),
  column('scourCountermeasureCondition', 'string'),
  column('postFloodInspectionRequired',  'boolean'),
  column('mitigationStatus',             'string',  { description: 'None Required | Planned | In Progress | Completed' }),
  column('assessor',                     'string'),
  column('inspectorAccreditationLevel',  'string'),
  column('nextReviewDate',               'date'),
  column('reportReference',              'string'),
  column('remarks',                      'string')
]

module.exports = {
  column,
  lookupDataset,
  LOOKUP_COLUMNS,
  ALLOWED_VALUES_COLUMNS,
  ALLOWED_VALUES_WHITELIST,
  BRIDGE_COLUMNS,
  RESTRICTION_COLUMNS,
  INSPECTION_COLUMNS,
  ELEMENT_COLUMNS,
  BRIDGE_RESTRICTION_COLUMNS,
  RST_PROVISION_COLUMNS,
  PROVISION_COLUMNS,
  LRC_COLUMNS,
  CONDITION_SURVEY_COLUMNS,
  LOAD_RATING_COLUMNS,
  PERMIT_COLUMNS,
  DEFECT_COLUMNS,
  CAPACITY_COLUMNS,
  SCOUR_COLUMNS
}
