'use strict';

const express = require('express');
const router  = express.Router();
router.use(express.json());

router.get('/bridges/:id/qr', async (req, res) => {
  try {
    const QRCode = require('qrcode');
    const { id } = req.params;
    const baseUrl = process.env.APP_BASE_URL || 'https://bms.tfnsw.gov.au';
    const url = `${baseUrl}/bridge/${id}`;
    const png = await QRCode.toBuffer(url, { type: 'png', width: 300, margin: 2 });
    res.set('Content-Type', 'image/png');
    res.set('Content-Disposition', `inline; filename="bridge-${id}-qr.png"`);
    res.send(png);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

router.get('/inspections/:id/report', async (req, res) => {
  const cds = require('@sap/cds');
  try {
    const { BridgeInspections, BridgeInspectionElements, Bridges } = cds.entities('bridge.management');
    const insp = await SELECT.one.from(BridgeInspections).where({ ID: req.params.id });
    if (!insp) return res.status(404).send('Inspection not found');

    const bridge = insp.bridge_ID ? await SELECT.one.from(Bridges).where({ ID: insp.bridge_ID }) : null;
    const elements = await SELECT.from(BridgeInspectionElements).where({ inspection_ID: req.params.id });

    const css = `
      body { font-family: Arial, sans-serif; font-size: 12px; color: #333; margin: 20px; }
      h1   { font-size: 18px; color: #003366; border-bottom: 2px solid #003366; padding-bottom: 4px; }
      h2   { font-size: 14px; color: #003366; margin-top: 20px; }
      table { width: 100%; border-collapse: collapse; margin-top: 8px; }
      th    { background: #003366; color: white; padding: 6px; text-align: left; font-size: 11px; }
      td    { padding: 5px 6px; border-bottom: 1px solid #ddd; }
      .kv   { display: grid; grid-template-columns: 200px 1fr; gap: 4px 12px; margin-bottom: 12px; }
      .kv label { font-weight: bold; color: #555; }
      .no-print { display: none; }
      @media print { .no-print { display: none; } body { margin: 0; } }
    `;

    const elementRows = elements.map(e => `
      <tr>
        <td>${e.elementType || ''}</td>
        <td>${e.conditionState1Qty || 0}</td>
        <td>${e.conditionState2Qty || 0}</td>
        <td>${e.conditionState3Qty || 0}</td>
        <td>${e.conditionState4Qty || 0}</td>
        <td>${e.unit || ''}</td>
        <td>${e.elementHealthRating != null ? e.elementHealthRating.toFixed(1) : ''}</td>
      </tr>`).join('');

    const html = `<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>Inspection Report — ${insp.inspectionRef || insp.ID}</title>
<style>${css}</style></head>
<body>
<div class="no-print"><button onclick="window.print()">Print / Save as PDF</button></div>
<h1>Bridge Inspection Report</h1>
<div class="kv">
  <label>Inspection Ref:</label><span>${insp.inspectionRef || insp.ID}</span>
  <label>Bridge:</label><span>${bridge ? bridge.bridgeName + ' (' + bridge.bridgeId + ')' : insp.bridge_ID}</span>
  <label>Inspection Date:</label><span>${insp.inspectionDate || ''}</span>
  <label>Type:</label><span>${insp.inspectionType || ''}</span>
  <label>Inspector:</label><span>${insp.inspector || ''}</span>
  <label>Overall Condition:</label><span>${insp.overallConditionRating != null ? insp.overallConditionRating : ''}</span>
  <label>Structural Adequacy:</label><span>${insp.structuralAdequacyRating != null ? insp.structuralAdequacyRating : ''}</span>
  <label>Status:</label><span>${insp.inspectionStatus || ''}</span>
</div>
${elements.length ? `
<h2>Element Condition States</h2>
<table><thead><tr>
  <th>Element Type</th><th>CS1 Good</th><th>CS2 Satisfactory</th><th>CS3 Poor</th><th>CS4 Failed</th><th>Unit</th><th>Health Rating</th>
</tr></thead><tbody>${elementRows}</tbody></table>` : ''}
${insp.inspectionNotes ? `<h2>Inspection Notes</h2><p>${insp.inspectionNotes}</p>` : ''}
<p style="margin-top:30px; font-size:10px; color:#999;">
  Generated by Bridge Management System — ${new Date().toISOString().slice(0,10)}
</p>
</body></html>`;

    res.set('Content-Type', 'text/html');
    res.send(html);
  } catch (err) {
    res.status(500).send(`<pre>${err.message}</pre>`);
  }
});

module.exports = router;
