const cds = require('@sap/cds')

const registerCommonHelpers        = require('./handlers/common')
const registerDashboardHandlers    = require('./handlers/dashboard')
const registerBridgeHandlers       = require('./handlers/bridges')
const registerRestrictionHandlers  = require('./handlers/restrictions')
const registerUploadHandlers       = require('./handlers/upload')
const registerAdminHandlers        = require('./handlers/admin')
const registerMassEditHandlers     = require('./handlers/mass-edit')
const registerLoadRatingHandlers   = require('./handlers/load-ratings')
const registerRiskAssessmentHandlers = require('./handlers/risk-assessments')
const registerNhvrComplianceHandlers = require('./handlers/nhvr-compliance')
const registerElementHandlers      = require('./handlers/elements')
const registerDefectHandlers       = require('./handlers/defects')
const registerInspectionHandlers   = require('./handlers/inspections')
const registerAlertHandlers        = require('./handlers/alerts')
const registerConditionHandlers    = require('./handlers/conditions')
const registerLoadRatingsNewHandlers = require('./handlers/load-ratings-new')
const registerPermitHandlers       = require('./handlers/permits')

module.exports = class BridgeManagementService extends cds.ApplicationService { init() {

    const helpers = registerCommonHelpers(this)

    registerDashboardHandlers(this, helpers)
    registerBridgeHandlers(this, helpers)
    registerRestrictionHandlers(this, helpers)
    registerUploadHandlers(this, helpers)
    registerAdminHandlers(this, helpers)
    registerMassEditHandlers(this, helpers)
    registerLoadRatingHandlers(this)
    registerRiskAssessmentHandlers(this)
    registerNhvrComplianceHandlers(this)
    registerElementHandlers(this)
    registerDefectHandlers(this)
    registerInspectionHandlers(this, helpers)
    registerAlertHandlers(this)
    registerConditionHandlers(this, helpers)
    registerLoadRatingsNewHandlers(this, helpers)
    registerPermitHandlers(this, helpers)

    // Map View — inline (no external state needed)
    this.on('geocodeAddress',  req => ({ latitude: null, longitude: null, formattedAddress: req.data.address }))
    this.on('reverseGeocode',  req => ({ address: '', suburb: '', state: '', postcode: '' }))
    this.on('getMapApiConfig', req => ({ provider: 'OSM', apiKey: '', defaultZoom: 6 }))

    return super.init()
}}
